apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkerc5783-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkerc5783-tenant-component
    app.kubernetes.io/part-of: loadkerc5783-tenant-app
  name: loadkerc5783-tenant-component
  namespace: loadkerc5783-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadkerc5783-tenant-component
    weight: null
status: {}
