apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkerc5783-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkerc5783-tenant-component
    app.kubernetes.io/part-of: loadkerc5783-tenant-app
  name: loadkerc5783-tenant-component
  namespace: loadkerc5783-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadkerc5783-tenant-component
status:
  loadBalancer: {}
